name: "Pending Response Follow Up"
description: "Add and remove `response` issue labels on new comments based on team membership."
author: siegerts
branding:
  color: blue
  icon: code
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: true
  member-associations:
    #https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
    description: 'Repository associations that are considered part of the team. Separate multiple with commas (eg. "OWNER, MEMBER")'
    default: "OWNER, MEMBER, COLLABORATOR"
  pending-response-label:
    description: Label to remove indicating that a response is required for further action
    required: true
  actionable-label:
    description: Label added to highlight that a user has responded and a follow-up is required

runs:
  using: "node12"
  main: "dist/index.js"
