name: pending-response
on: issue_comment

jobs:
  issue_commented:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          member-associations: "OWNER, MEMBER, COLLABORATOR"
          pending-response-label: pending-response
          actionable-label: follow-up
